name: momentum_track
description: "Manage your momentum with this app. Track your progress and stay motivated."
version: 1.3.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  intl: ^0.20.2
  gap: ^3.0.1
  path: ^1.9.1
  logger: ^2.5.0
  file_picker: ^10.0.0
  sqlite3: ^2.7.5
  window_manager: ^0.4.3
  hugeicons: ^0.0.10
  shamsi_date: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  package_rename: ^1.9.0
  flutter_launcher_icons: "^0.14.3"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/luncher/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700